### ISSUE TITLE
New post/comment removes unescaped characters

### ISSUE THREAD

**Issue by phedoreanu** [diaspora/diaspora-project-site#110]
Hey guys,

`\:D/` after saving turns into `:D/`.

Need to post `\\:D/` for the correct text to appear.

Thanks!

**Comment by SuperTux88** [comment]
I think this isn't related to the project site, did you want to create an issue for [diaspora](https://github.com/diaspora/diaspora) itself?

Anyway, I don't think this is a bug, because `\` used for escaping is mentioned in the [spec](http://spec.commonmark.org/0.27/#backslash-escapes). And since diaspora uses [markdown-it](https://github.com/markdown-it/markdown-it) you would need to create an issue there if you still think it's a bug.
