### ISSUE TITLE
Regarding responsiveness of the website 

### ISSUE THREAD

**Issue by riyak1998** [diaspora/diaspora-project-site#118]
Hey!
I have noticed some issues with the responsiveness of this website. Once it shifts to responsive view, it doesn't shift back to the regular laptop view, even on increasing screen size. This causes problems while development. Also, it can cause an issue in portrait and landscape mode on smaller devices.

Me and my teammate @Amritha777 would love to work on the responsiveness of this website. As we both are well versed in frontend designing with HTML, CSS, and JS. We are pretty much experienced in Bootstrap framework as well. 
Also, we would love to contribute it as a part of **RGSOC'18 applications**.

PS: I am enclosing a screenshot for the same.

![whatsapp image 2018-02-27 at 1 48 21 am](https://user-images.githubusercontent.com/32415489/36695764-3e36b54a-1b68-11e8-8d9b-1aa626fc25f0.jpeg)

**Comment by Flaburgan** [comment]
@riyak1998, this repository is about the website hosted at https://diasporafoundation.org, not the diaspora software. To answer your remark, this is the mobile version of diaspora*. It is not "responsive", it has been conceived specially for small and touch screen.

You can switch between the mobile and the desktop version by using the "toggle mobile" link (in the drawer, in the footer...). Note that the desktop version itself is kind of responsive, so it's not always easy to difference both version :P Tip: when there is a "write a post" icon in the header, it is the mobile version.

**Comment by denschub** [comment]
In addition to what @Flaburgan said...

> Also, we would love to contribute it as a part of RGSOC'18 applications.

While I appreciate your enthusiasm, as I mentioned on IRC already, it's probably best to wait until you have an official go from the RGSoC group. There is no reason to hurry, because you won't be able to bring a pull request in before the application deadline runs out, and there is plenty of time afterwards! Given the official working time starts in June, a lot may change until then.

The issue with the project website is already reported by you in #117, and this issue is related to diaspora itself, not the website. As such, it's in the wrong repo. Although this is off-topic here, let me also add that, while I appreciate you wanting to work on the mobile frontend, it might actually not be a good idea to invest huge amounts (an entire summer, that is) of time in it, since [we are planning to completely reengineering our frontend](https://discourse.diasporafoundation.org/t/choosing-new-frontend-framework/1070) some time in the future anyway.

Take your time, find some tasks that look interesting to you, and talk to your RGSoC mentors and Lisa about that. There is plenty of time after that to get started with developing it. :)

**Comment by riyak1998** [comment]
@Flaburgan Hey, what I meant was that even though I'm accessing the site through my laptop, the mobile site is showing up.

On login, the page seems good, made for viewing on the laptop. However, I checked for responsiveness (by clicking on toggle mobile in DevTools). The mobile site showed up perfectly. However, after toggling back to the laptop view, the site didn't change into laptop view, it continued to display the mobile site. This is the issue I'm referring to.

**Comment by Flaburgan** [comment]
@riyak1998 I already heard about such a problem (a computer being detected as mobile, so the mobile version is displayed) but I'm not able to find an issue about it at this time. Please open an issue at https://github.com/diaspora/diaspora/issues/new with details about your computer model, browser and OS versions, possibly screen size. Thank you.

**Comment by riyak1998** [comment]
@denschub I started using diaspora* and found some issues. The main task that I wanted to solve today was to find as many issues as I can, which could be solved at some later date. However, as you mentioned that you're about to shift the front-end to React, I'll stop with front-end bugs now.

I've already started learning React, and would love to contribute to this aspect of the project (i.e. porting to React). Can you point me to the relevant discussions/forum from where I can get an idea about what is the current state of this task?

**Comment by denschub** [comment]
> Can you point me to the relevant discussions/forum from where I can get an idea about what is the current state of this task?

https://discourse.diasporafoundation.org/t/choosing-new-frontend-framework/1070, as I've linked in my previous comment. :)
