### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora-project-site#89]
The sentence "If you have already signed up, you can skip this section and go straight to (part 2)" is in english on the website set to french. This segment doesn't appear on webtranslateit and all the locales have been pushed, this means there is a bug in the source file. Here is the problematic line: https://github.com/diaspora/diaspora-project-site/search?utf8=%E2%9C%93&q=find_pod_intro&type=Code I don't know what's the mistake actually.

**Comment by goobertron** [comment]
The string 'pages.getting_started1.find_pod_intro' doesn't appear in the current `master` version of `config/en.yml`. I'm not sure how this happened, although it is most likely my fault because of my attempt to standardise quote marks in the `en.yml` file, which Dennis had to fix on the fly. Reinstating that string should fix the problem.

It was introduced in https://github.com/diaspora/diaspora-project-site/commit/ec91c0af4d24f1d3cfaa263a9c2576b029e85338. You can find it here: https://github.com/diaspora/diaspora-project-site/blob/93eb6a763d45eeed2c1325e8973db5bae6e99f46/config/locales/en.yml#L239

and the text is:

`find_pod_intro: "If you have already signed up, you can skip this section and go straight to %{part2_link}."`
