### ISSUE TITLE
Many images broken in the tutorials

### ISSUE THREAD

**Issue by Flaburgan** [diaspora/diaspora-project-site#91]
On https://diasporafoundation.org/getting_started/interface for example, many images are not displayed. I'll have a look at that.

**Comment by goobertron** [comment]
The things I see missing are text strings, not images. See my explanation in https://github.com/diaspora/diaspora-project-site/issues/89#issuecomment-2685111763 - I think this is the same problem. At some point since my PR to update the tutorials, `config.en.yml` has been rolled back to a previous version, which doesn't include the strings I introduced in that PR.

Paging @denschub for advice.
